spring:
  profiles:
    default: dev
  thymeleaf:
    cache: false
    prefix: file:calendar-api/src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
  datasource:
    url: jdbc:mysql://localhost:3306/calendar_db?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: debug